python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11

mpi:
  - nompi
  - mpich

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.12                       # [linux and x86_64]
  - 2.17                       # [linux and not x86_64]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
