{% set name = "pymeep" %}
{% set version = "1.15.0" %}
{% set sha256 = "be50ccded3f1fb97e5c3a4e0351e2ff864d2a94c95ed80e29613d63a72c371f7" %}
{% set buildnumber = 3 %}
# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set buildnumber = buildnumber + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: meep-{{ version }}.tar.gz
  url: https://github.com/NanoComp/meep/releases/download/v{{ version }}/meep-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ buildnumber }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on mpi or nompi variants
  # dependencies:
  #     `pymeep * mpi_mpich_*` for mpich
  #     `pymeep * mpi_*` for any mpi
  #     `pymeep * nompi_*` for no mpi
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ buildnumber }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}

  host:
    - libblas >=3.8
    - libcblas >=3.8
    - liblapack >=3.8
    - libgdsii >=0.21
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py >=3.0  # [mpi != 'nompi']
    - python
    - libctl >=4.5
    - harminv >=1.4.1
    - mpb >=1.10 {{ mpi_prefix }}_*
    - hdf5 1.10.5 {{ mpi_prefix }}_*
    - numpy 1.16
    - gsl

  run:
    # more or less a copy of the specs above
    - libblas >=3.8
    - libcblas >=3.8
    - liblapack >=3.8
    - libgdsii >=0.21
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py >=3.0  # [mpi != 'nompi']
    - python
    - libctl >=4.5
    - harminv >=1.4.1
    - mpb >=1.10 {{ mpi_prefix }}_*
    - hdf5 1.10.5 {{ mpi_prefix }}_*
    - {{ pin_compatible('numpy') }}

    # extras needed or typically used at runtime
    - h5utils * {{ mpi_prefix }}_*
    - h5py * {{ mpi_prefix }}_*
    - matplotlib-base >=2.2
    - scipy
    - mayavi
    - autograd
    - ffmpeg
    - zlib
    - libopenblas
    - fftw

test:
  requires:
    - parallel
  imports:
    - meep
    - meep.mpb
  source_files:
    - tests/cyl-ellipsoid-eps-ref.h5
    - python/tests/*.py
    - python/tests/data/*

about:
  home: https:/github.com/NanoComp/meep
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Free finite-difference time-domain (FDTD) software for electromagnetic simulations
  doc_url: https://meep.readthedocs.io
  dev_url: https://github.com/NanoComp/meep

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
    - RobinD42
