{% set name = "pymeep" %}
{% set version = "1.15.0" %}
{% set sha256 = "be50ccded3f1fb97e5c3a4e0351e2ff864d2a94c95ed80e29613d63a72c371f7" %}
{% set buildnumber = 1 %}
# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set buildnumber = buildnumber + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: meep-{{ version }}.tar.gz
  url: https://github.com/NanoComp/meep/releases/download/v{{version}}/meep-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ buildnumber }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pymeep * mpi_mpich_*` for mpich
  # `pymeep * mpi_*` for any mpi
  # `pymeep * nompi_*` for no mpi
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ buildnumber }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - libctl >=4.5.0
    - harminv
    - mpb >=1.10.0 {{ mpi_prefix }}_*
    - gsl
    - hdf5 1.10.4 {{ mpi_prefix }}_*
    - numpy 1.11.*
    - mpi4py 3.0.*  # [mpi != 'nompi']
    - libgdsii >=0.21
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - libctl >=4.5.0
    - harminv
    - mpb
    - {{ pin_compatible('numpy') }}
    - hdf5
    - gsl
    - h5utils * {{ mpi_prefix }}_*
    - h5py * {{ mpi_prefix }}_*
    - scipy
    - mpi4py 3.0.*  # [mpi != 'nompi']
    - matplotlib >=2.2
    - libgdsii >=0.21
    - ffmpeg >=4.0
    - mayavi
    - autograd

test:
  requires:
    - parallel
  imports:
    - meep
    - meep.mpb
  source_files:
    - tests/cyl-ellipsoid-eps-ref.h5
    - python/tests/*.py
    - python/tests/data/*

about:
  home: http:/github.com/NanoComp/meep
  license: GPL-2.0
  license_file: LICENSE
  summary: Free finite-difference time-domain (FDTD) software for electromagnetic simulations
  doc_url: http://meep.readthedocs.io
  dev_url: https://github.com/NanoComp/meep

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
